version: "3.3"
services:

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: unless-stopped
    volumes:
      - jenkins-data:/var/jenkins_home:rw
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-public"
      - "traefik.http.routers.jenkins.rule=Host(`${HOSTNAME}`)"
      - "traefik.http.routers.jenkins.service=jenkins"
      - "traefik.http.services.jenkins.loadbalancer.server.port=8080"
      - "traefik.http.routers.jenkins.entrypoints=websecure"
      - "traefik.http.routers.jenkins.tls.certresolver=letsencrypt"
      - "traefik.http.routers.jenkins.tls=true"

    networks:
      - jenkins-network
      - traefik-public
    logging:
      driver: "json-file"
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

  agent:
    image: jenkins/ssh-agent:jdk11
    container_name: jenkins-worker
    expose:
    - 22
    environment:
    - JENKINS_AGENT_SSH_PUBKEY=${SSH_PUB_KEY}
    networks:
      - jenkins-network

networks:
  traefik-public:
    external: true
  jenkins-network:
    external: false

volumes:
  jenkins-data: